### ISSUE TITLE
Template for new DataMap slash too much

### ISSUE THREAD

**Issue by cadon** [alex4401/mediawiki-extensions-DataMaps#184]
**One slash too much in template for new data map**
When creating a new data map, the page `Map:MyMapName` contains a json with a preset `$schema` property linking to a json file. In the uri of that file after the top level domain there is one `/` too much, making the uri invalid.

**To Reproduce**
1. Create new map
2. Click on the Edit button in the map at the top right
3. The pre filled json template has the property `"$schema": "https://myWikiName.wiki.gg//extensions/DataMaps/schemas/v0.16.json"`, directly after `.gg` there are two `//` instead of just one, making the uri invalid.

**Expected behavior**
Only one slash in the uri.

**Comment by alex4401** [comment]
Fix is in the `main` branch, will ask for a deployment when v0.16.7 is ready in ~two days.

**Comment by alex4401** [comment]
I've requested a deployment a few days ago but it still doesn't seem to have happened. I'll wait until Monday evening and will submit it as a ticket if it's not done yet.

**Comment by cadon** [comment]
No hurry, this issue appears only once a new map is created and it's easy to fix manually, so just a minor issue.

**Comment by alex4401** [comment]
Seems to have been deployed now, issue looks to be fixed.
