### ISSUE TITLE
Exception when adding `image` to Marker

### ISSUE THREAD

**Issue by cadon** [alex4401/mediawiki-extensions-DataMaps#190]
**Describe the bug**
When adding a property `image` with the name of an existing file to a marker entry a `Fatal exception of type "Error"` occurs when saving or previewing.

**To Reproduce**
Currently the properties look like this at https://superfantasykingdom.wiki.gg/wiki/Map:Kingdom
```
	"groups": {
		"buildings": {
			"name": "Buildings",
			"fillColor": "#ff0000", "borderColor": "#fff", "size": 5.5, "icon": "House.png"
		},
		"resources": {
			"name": "Resources",
			"fillColor": "#00ff00", "borderColor": "#fff", "size": 5.5, "icon": "Wood.png"
		}
	},
	"markers": {
		"buildings": [
			{
				"x": 363, "y": 670,
				"name": "Castle",
				"description": "[[Castle]]"
			}
		],
		"resources": [
			{
				"x": 396, "y": 797,
				"name": "Tree",
				"description": "[[Tree]]s can be cut down to get [[Wood]]"
			}
		]
	}
```
When adding an image property to the last marker object like
```
			{
				"x": 396, "y": 797,
				"name": "Tree",
				"description": "[[Tree]]s can be cut down to get [[Wood]]",
				"image": "Tree.png"
			}
```
and click save or preview, the fatal error occurs.
Using an empty value for the image property or a name of a non-existing file will give an error message with that explained. Only when entering an existing filename the exception occurs.

**Comment by alex4401** [comment]
Seems like this is the issue d8504fa was for, which will be included in v0.16.7/next deployment.

(Also, you can try `pinColor` instead of `fillColor` if you'd prefer pins instead of circles. Just spreading awareness.)
