### ISSUE TITLE
z-index issue between layer toggle popups and other buttons in group

### ISSUE THREAD

**Issue by cadon** [alex4401/mediawiki-extensions-DataMaps#195]
**Describe the bug**
When too many layer options are available, wrapping the toggle buttons in a second row, the toggle buttons in lower rows overlap the popup of toggle buttons of the rows above.

**To Reproduce**
Example map: https://ark.wiki.gg/wiki/Resource_Map/Genesis:_Part_2
There are 4 toggle buttons: `Show all` `Hide all` `Toggle` `Asteroids`. The last button is wrapped in the second row. When opening the popup of the third button (`Toggle`), the button in the second row (`Asteroids`) overlaps the popup, making it hard to read the text and to toggle the checkboxes of the layer groups.
The issue seems to come from the css rule
```
.oo-ui-buttonGroupWidget .oo-ui-buttonElement {
  z-index: 0;
}
```
Removing the z-index part of the rule (or replace the z-index `0` with `auto`), seems to fix the issue. Not sure if this will break something else.

**Expected behavior**
No overlap of the currently opened popup.

**Comment by alex4401** [comment]
Thanks!

This is looking like an OOUI issue (the rule is not from my extension), so I'm curious why the depth index is changed on button group buttons.

I'll include a fix in the next release, but for now add the following rule to your site CSS (via MediaWiki:DataMaps.css):
```css
.ext-datamaps-control-expandable-content .oo-ui-buttonGroupWidget .oo-ui-buttonElement {
  z-index: unset;
}
```
